apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name}}
  namespace: {{ .Values.app.namespace}}

spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app.name}}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name}}
    spec:
      containers:
        - name: {{ .Values.app.name}}
          image: {{ .Values.app.image}}
          resources:
            limits:
              memory: {{ .Values.app.resources.limits.memory}}
              cpu: {{ .Values.app.resources.limits.cpu}}
            requests:
              memory: {{ .Values.app.resources.requests.memory}}
              cpu: {{ .Values.app.resources.requests.cpu}}
          ports:
            - containerPort: 8200
